package br.com.zup.gerenciamentoEscolar.enums;

public enum TipoLogEvento {
    LISTOU_ALUNOS,
    LISTOU_ALUNO,
    LISTOU_CURSOS,
    LISTOU_CURSO,
    LISTOU_MATRICULAS,
    LISTOU_MATRICULA,
    LISTOU_PROFESSORES,
    LISTOU_PROFESSOR,
    ALUNO_NAO_ENCONTRADO,
    CURSO_NAO_ENCONTRADO,
    MATRICULA_NAO_ENCONTRADA,
    PROFESSOR_NAO_ENCONTRADO,
    ALUNO_CADASTRADO,
    CURSO_CADASTRADO,
    MATRICULA_CADASTRADA,
    PROFESSOR_CADASTRADO,
    ALUNO_DELETADO,
    CURSO_DELETADO,
    MATRICULA_DELETADA,
    PROFESSOR_DELETADO,
    MATRICULA_ATUALIZADA
}
